version: '3.9'

services:
  proxy:
    container_name: nl-ex-proxy
    build: ./infra/nginx
    ports: 
      - 80:80
      - 8080:8080
    volumes:
      - ./frontend:/usr/share/nginx/html/app
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - frontend
      - backend
  
  backend:
    container_name: nl-ex-be
    build: ./infra/php
    restart: always
    ports: 
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
      - ./infra/php/php.ini:/usr/local/php/php.ini
    depends_on:
      - db
  
  frontend:
    container_name: nl-ex-fe
    build: ./infra/node
    tty: true
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

  db:
    container_name: nl-ex-db
    build: ./infra/mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: nl-ex_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: firstuser
      MYSQL_PASSWORD: firstpassword
      TZ: Asia/Tokyo

  phpmyadmin:
    container_name: nl-ex-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=rootpassword

volumes:
  db-store:
